service: py-hello-world

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: us-west-1

functions:
  hello-string:
    handler: app/string-handler.hello
    name: hello-string
  hello-json:
    handler: app/json-handler.hello
    name: hello-json
